name: CI/CD Pipeline for Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PEM file
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > mandi.pem
          chmod 600 mandi.pem

      - name: Transfer files to EC2
        run: |
          rsync -avz -e "ssh -i mandi.pem -o StrictHostKeyChecking=no" --delete-after ./ ubuntu@43.201.250.130:/var/www/html/AWS_FinalProject

      - name: Restart Nginx
        run: |
          ssh -i mandi.pem -o StrictHostKeyChecking=no ubuntu@43.201.250.130 "sudo systemctl restart nginx"
